import type { Metadata } from "next";
import "./globals.css";
import AppLayout from "@/components/layouts";


export const metadata: Metadata = {
  title: "Save A Repo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
